
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

joinfaces:
  primefaces:
  #theme: twitter
  jsf:
    project-stage: Development
    facelets-refresh-period: 0
    state-saving-method: client
    serialize-server-state: true

logging:
  level:
    root: INFO
    org.apache.http: INFO
    net.ravendb.client: WARN
    org.gpc4j.health.watch.jsf.beans.WorkoutBean: DEBUG
  pattern:
    dateformat: MM-dd HH:mm:ss.SSS,America/Los_Angeles
    console: "${CONSOLE_LOG_PATTERN:-%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr(%-25.35logger{1}.%M){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"
